/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Crono;
import javax.swing.JOptionPane;

/**
 *
 * @author ProgInit
 */
public class Config extends javax.swing.JFrame {

    /**
     * Creates new form Config
     */
    public Config() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Thread hilo;
    //boolean cronometroActivo;
    
    //public void iniciarCronometro() {
        //diah();
    //}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jcb_set = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jcb_servidor = new javax.swing.JComboBox<>();
        btn_iniciar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_jug1 = new javax.swing.JLabel();
        lbl_jug2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Juegos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jcb_set.setBackground(new java.awt.Color(255, 255, 255));
        jcb_set.setForeground(new java.awt.Color(0, 51, 51));
        jcb_set.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "3", "5", "7" }));
        jcb_set.setBorder(null);
        jcb_set.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jcb_set, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SERVIDOR");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jcb_servidor.setBackground(new java.awt.Color(255, 255, 255));
        jcb_servidor.setForeground(new java.awt.Color(0, 51, 51));
        jcb_servidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        jcb_servidor.setBorder(null);
        jcb_servidor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jcb_servidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        btn_iniciar.setBackground(new java.awt.Color(255, 255, 255));
        btn_iniciar.setForeground(new java.awt.Color(0, 51, 51));
        btn_iniciar.setText("INICIAR");
        btn_iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/hombre-jugando-al-ping-pong.png"))); // NOI18N
        jLabel7.setText("JUGADOR 1:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 40));

        jLabel8.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/man-jugando-ping-pong.png"))); // NOI18N
        jLabel8.setText("JUGADOR 2:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 40));

        lbl_jug1.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        lbl_jug1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jug1.setText("jLabel9");
        jPanel1.add(lbl_jug1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        lbl_jug2.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        lbl_jug2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jug2.setText("jLabel10");
        jPanel1.add(lbl_jug2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        Game g = new Game();
       
        //g.iniciarCronometro();
        String juga1 = lbl_jug1.getText();
        String juga2 = lbl_jug2.getText();
        g.lbl_jugador1.setText(juga1);
        g.lbl_jugador2.setText(juga2);
        String se = jcb_set.getSelectedItem().toString();
        String s = jcb_servidor.getSelectedItem().toString();
        String s1 = "1";
        String s2 = "2";
        if(s.equals(s1)){
            g.lbl_jset.setText(juga1);
            g.lbl_pelota1.setVisible(true);
            g.lbl_pelota2.setVisible(false);
        }
        if(s.equals(s2)){
                g.lbl_jset.setText(juga2);
                g.lbl_pelota1.setVisible(false);
                g.lbl_pelota2.setVisible(true);
            }
        g.lbl_set.setText(se);
        g.iniCrono();
        
        g.setVisible(true);
        dispose();
        //if(jcb_servidor.getText() == 1){
            
        //}
        //new Arbitro();
        /*if(txt_nombreJ1.getText().isEmpty()||txt_apellidoJ1.getText().isEmpty()||txt_nombreJ2.getText().isEmpty()||txt_apellidoJ2.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Llenar todo los campos POR FAVOR");
        }else{
            Game g = new Game();
            //g.setVisible(true);
            String jugadorN1 = txt_nombreJ1.getText();
            //String jugadorA1 = txt_apellidoJ1.getText();
            String jugadorN2 = txt_nombreJ2.getText();
            //String jugadorA2 = txt_apellidoJ2.getText();
            //g.lbl_jugador1.setText(jugadorN1+" "+jugadorA1);
           // g.lbl_jugador2.setText(jugadorN2+" "+jugadorA2);
            g.lbl_jugador1.setText(jugadorN1);
            g.lbl_jugador2.setText(jugadorN2);
            g.iniciarCronometro();
            g.btn_play.setEnabled(false);
            this.dispose();
        }*/
    }//GEN-LAST:event_btn_iniciarActionPerformed

    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        dispose();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcb_servidor;
    private javax.swing.JComboBox<String> jcb_set;
    public javax.swing.JLabel lbl_jug1;
    public javax.swing.JLabel lbl_jug2;
    // End of variables declaration//GEN-END:variables
}
