package Vista;
import Clases.Punto;
import java.awt.Color;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
/**
 *
 * @author ProgInit
 */
public class Game extends javax.swing.JFrame implements Runnable{
    Thread hilo;
    String hora, minutos, segundos;
    
    private int seg = 0;
    private int min = 0;
    private int hor = 0;
    private boolean continuar = true;
//    private Cronometro_Partido i;
    public int n=0;
    public int count = 0;
    public int ne,p2;
    private Timer t;
    private int h, m, s, cs;
    

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        this.setLocationRelativeTo(null);
        hilo = new Thread(this);
        hilo.start();
        
        t = new Timer(10, acciones);
        
        if(n==0){
            lbl_pelota1.setVisible(false);
            lbl_pelota2.setVisible(false);
        }
        
    }
    
    private ActionListener acciones = new ActionListener(){

        @Override
        public void actionPerformed(ActionEvent ae) {
            ++cs; 
            if(cs==100){
                cs = 0;
                ++s;
            }
            if(s==60) 
            {
                s = 0;
                ++m;
            }
            if(m==60)
            {
                m = 0;
                ++h;
            }
            actualizarLabel();
        }
        
    };
    
    private void actualizarLabel() {
        String tiempo = (h<=9?"0":"")+h+":"+(m<=9?"0":"")+m+":"+(s<=9?"0":"")+s+":"+(cs<=9?"0":"")+cs;
        lbl_cronoPartido.setText(tiempo);
    }
    
    public void iniCrono(){
        t.start();       
    }
    
    //Thread hilo  
    
    public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date hora_actual = new Date();
        calendario.setTime(hora_actual);
        hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
        
    }
    
    public void run(){
        Thread current = Thread.currentThread();
        while(current == hilo){
            hora();
            lbl_horaAct1.setText(hora+":"+minutos+":"+segundos);
        }              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpvista1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_horaAct1 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        lbl_cronoPartido = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jpvista2 = new javax.swing.JPanel();
        lbl_jugador1 = new javax.swing.JLabel();
        lbl_jugador2 = new javax.swing.JLabel();
        jpvistaIzq = new javax.swing.JPanel();
        btn_MenIzq = new javax.swing.JButton();
        lbl_pelota1 = new javax.swing.JLabel();
        btn_MasIzq = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_NumIzq = new javax.swing.JLabel();
        jp_tarjetaIzq = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpvistaDerech = new javax.swing.JPanel();
        btn_MenDer = new javax.swing.JButton();
        btn_MasDer1 = new javax.swing.JButton();
        lbl_pelota2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_NumDer = new javax.swing.JLabel();
        jp_tarjetaDer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpvista3 = new javax.swing.JPanel();
        lbl_puntuacion1 = new javax.swing.JLabel();
        jpvista4 = new javax.swing.JPanel();
        lbl_puntuacion2 = new javax.swing.JLabel();
        jpvista5 = new javax.swing.JPanel();
        btn_minJ1 = new javax.swing.JButton();
        btn_minJ2 = new javax.swing.JButton();
        jpvista7 = new javax.swing.JPanel();
        lbl_set = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_jset = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpvista1.setBackground(new java.awt.Color(0, 51, 51));
        jpvista1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HORA");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CRONOMETRO");

        lbl_horaAct1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        lbl_horaAct1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_horaAct1.setText("00:00:00");

        btn_salir.setBackground(new java.awt.Color(0, 51, 51));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar.png"))); // NOI18N
        btn_salir.setBorder(null);
        btn_salir.setBorderPainted(false);
        btn_salir.setContentAreaFilled(false);
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        lbl_cronoPartido.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        lbl_cronoPartido.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cronoPartido.setText("00:00:00:00");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/youtube.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpvista1Layout = new javax.swing.GroupLayout(jpvista1);
        jpvista1.setLayout(jpvista1Layout);
        jpvista1Layout.setHorizontalGroup(
            jpvista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpvista1Layout.createSequentialGroup()
                .addGroup(jpvista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpvista1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addGap(199, 199, 199))
                    .addGroup(jpvista1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lbl_cronoPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGroup(jpvista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpvista1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpvista1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(lbl_horaAct1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        jpvista1Layout.setVerticalGroup(
            jpvista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpvista1Layout.createSequentialGroup()
                .addGroup(jpvista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpvista1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jpvista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpvista1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6)
                .addGroup(jpvista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpvista1Layout.createSequentialGroup()
                        .addComponent(lbl_horaAct1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(jpvista1Layout.createSequentialGroup()
                        .addComponent(lbl_cronoPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpvista1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel1.add(jpvista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        jpvista2.setBackground(new java.awt.Color(255, 255, 255));
        jpvista2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        lbl_jugador1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_jugador1.setForeground(new java.awt.Color(0, 51, 51));
        lbl_jugador1.setText("Jugador 1");
        lbl_jugador1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lbl_jugador2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbl_jugador2.setForeground(new java.awt.Color(0, 51, 51));
        lbl_jugador2.setText("Jugador 2");

        javax.swing.GroupLayout jpvista2Layout = new javax.swing.GroupLayout(jpvista2);
        jpvista2.setLayout(jpvista2Layout);
        jpvista2Layout.setHorizontalGroup(
            jpvista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpvista2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(lbl_jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jpvista2Layout.setVerticalGroup(
            jpvista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpvista2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpvista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jugador2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(lbl_jugador1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jpvista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1030, 50));

        jpvistaIzq.setBackground(new java.awt.Color(255, 255, 255));
        jpvistaIzq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        jpvistaIzq.setForeground(new java.awt.Color(0, 51, 51));
        jpvistaIzq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_MenIzq.setBackground(new java.awt.Color(255, 255, 255));
        btn_MenIzq.setForeground(new java.awt.Color(255, 255, 255));
        btn_MenIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menos_1.png"))); // NOI18N
        btn_MenIzq.setBorder(null);
        btn_MenIzq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MenIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenIzqActionPerformed(evt);
            }
        });
        jpvistaIzq.add(btn_MenIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        lbl_pelota1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tenisp.png"))); // NOI18N
        jpvistaIzq.add(lbl_pelota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, 40));

        btn_MasIzq.setBackground(new java.awt.Color(255, 255, 255));
        btn_MasIzq.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_MasIzq.setForeground(new java.awt.Color(255, 255, 255));
        btn_MasIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/mas1.png"))); // NOI18N
        btn_MasIzq.setBorder(null);
        btn_MasIzq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MasIzq.setRequestFocusEnabled(false);
        btn_MasIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MasIzqActionPerformed(evt);
            }
        });
        jpvistaIzq.add(btn_MasIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 30, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lbl_NumIzq.setFont(new java.awt.Font("Arial", 0, 80)); // NOI18N
        lbl_NumIzq.setForeground(new java.awt.Color(0, 51, 51));
        lbl_NumIzq.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_NumIzq)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_NumIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpvistaIzq.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jp_tarjetaIzq.setBackground(new java.awt.Color(255, 255, 255));
        jp_tarjetaIzq.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));
        jp_tarjetaIzq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_tarjetaIzq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_tarjetaIzqMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_tarjetaIzqLayout = new javax.swing.GroupLayout(jp_tarjetaIzq);
        jp_tarjetaIzq.setLayout(jp_tarjetaIzqLayout);
        jp_tarjetaIzqLayout.setHorizontalGroup(
            jp_tarjetaIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jp_tarjetaIzqLayout.setVerticalGroup(
            jp_tarjetaIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jpvistaIzq.add(jp_tarjetaIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 30, 40));

        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Tarjeta");
        jpvistaIzq.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jpvistaIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 350, 430));

        jpvistaDerech.setBackground(new java.awt.Color(255, 255, 255));
        jpvistaDerech.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        jpvistaDerech.setForeground(new java.awt.Color(0, 51, 51));
        jpvistaDerech.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_MenDer.setBackground(new java.awt.Color(255, 255, 255));
        btn_MenDer.setForeground(new java.awt.Color(255, 255, 255));
        btn_MenDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menos_1.png"))); // NOI18N
        btn_MenDer.setBorder(null);
        btn_MenDer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MenDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenDerActionPerformed(evt);
            }
        });
        jpvistaDerech.add(btn_MenDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        btn_MasDer1.setBackground(new java.awt.Color(255, 255, 255));
        btn_MasDer1.setForeground(new java.awt.Color(255, 255, 255));
        btn_MasDer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/mas1.png"))); // NOI18N
        btn_MasDer1.setBorder(null);
        btn_MasDer1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_MasDer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MasDer1ActionPerformed(evt);
            }
        });
        jpvistaDerech.add(btn_MasDer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 30, 30));

        lbl_pelota2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tenisp.png"))); // NOI18N
        jpvistaDerech.add(lbl_pelota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        lbl_NumDer.setFont(new java.awt.Font("Arial", 0, 80)); // NOI18N
        lbl_NumDer.setForeground(new java.awt.Color(0, 51, 51));
        lbl_NumDer.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_NumDer)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_NumDer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpvistaDerech.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jp_tarjetaDer.setBackground(new java.awt.Color(255, 255, 255));
        jp_tarjetaDer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 3, true));
        jp_tarjetaDer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_tarjetaDer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_tarjetaDerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_tarjetaDerLayout = new javax.swing.GroupLayout(jp_tarjetaDer);
        jp_tarjetaDer.setLayout(jp_tarjetaDerLayout);
        jp_tarjetaDerLayout.setHorizontalGroup(
            jp_tarjetaDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jp_tarjetaDerLayout.setVerticalGroup(
            jp_tarjetaDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jpvistaDerech.add(jp_tarjetaDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 30, 40));

        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Tarjeta");
        jpvistaDerech.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jPanel1.add(jpvistaDerech, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 350, 430));

        jpvista3.setBackground(new java.awt.Color(0, 51, 51));
        jpvista3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lbl_puntuacion1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        lbl_puntuacion1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_puntuacion1.setText("0");

        javax.swing.GroupLayout jpvista3Layout = new javax.swing.GroupLayout(jpvista3);
        jpvista3.setLayout(jpvista3Layout);
        jpvista3Layout.setHorizontalGroup(
            jpvista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpvista3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lbl_puntuacion1)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jpvista3Layout.setVerticalGroup(
            jpvista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpvista3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(lbl_puntuacion1)
                .addGap(52, 52, 52))
        );

        jPanel1.add(jpvista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 160, 160));

        jpvista4.setBackground(new java.awt.Color(0, 51, 51));
        jpvista4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lbl_puntuacion2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        lbl_puntuacion2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_puntuacion2.setText("0");

        javax.swing.GroupLayout jpvista4Layout = new javax.swing.GroupLayout(jpvista4);
        jpvista4.setLayout(jpvista4Layout);
        jpvista4Layout.setHorizontalGroup(
            jpvista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpvista4Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(lbl_puntuacion2)
                .addGap(58, 58, 58))
        );
        jpvista4Layout.setVerticalGroup(
            jpvista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpvista4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbl_puntuacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel1.add(jpvista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 150, 160));

        jpvista5.setBackground(new java.awt.Color(255, 255, 255));
        jpvista5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        btn_minJ1.setBackground(new java.awt.Color(0, 51, 51));
        btn_minJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cronometro.png"))); // NOI18N
        btn_minJ1.setText("T");
        btn_minJ1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minJ1ActionPerformed(evt);
            }
        });

        btn_minJ2.setBackground(new java.awt.Color(0, 51, 51));
        btn_minJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cronometro.png"))); // NOI18N
        btn_minJ2.setText("T");
        btn_minJ2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minJ2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpvista5Layout = new javax.swing.GroupLayout(jpvista5);
        jpvista5.setLayout(jpvista5Layout);
        jpvista5Layout.setHorizontalGroup(
            jpvista5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpvista5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btn_minJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(btn_minJ2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jpvista5Layout.setVerticalGroup(
            jpvista5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpvista5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jpvista5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_minJ1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btn_minJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jpvista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 330, 60));

        jpvista7.setBackground(new java.awt.Color(255, 255, 255));

        lbl_set.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        lbl_set.setForeground(new java.awt.Color(0, 51, 51));
        lbl_set.setText("jLabel4");

        jLabel3.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("SET:");

        javax.swing.GroupLayout jpvista7Layout = new javax.swing.GroupLayout(jpvista7);
        jpvista7.setLayout(jpvista7Layout);
        jpvista7Layout.setHorizontalGroup(
            jpvista7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpvista7Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_set)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jpvista7Layout.setVerticalGroup(
            jpvista7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpvista7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpvista7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_set)
                    .addComponent(jLabel3))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jpvista7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 330, 80));

        lbl_jset.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        lbl_jset.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jset.setText("JUEGOS");
        jPanel1.add(lbl_jset, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Servidor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MasDer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MasDer1ActionPerformed
        count++;
        String numero = String.valueOf(count);
        //prueba.setText(numero);
        
        if(count==2){
            lbl_pelota1.setVisible(false);
            lbl_pelota2.setVisible(true);
        }
        if(count==4){
            lbl_pelota1.setVisible(true);
            lbl_pelota2.setVisible(false);
        }
         if(count==6){
            lbl_pelota1.setVisible(false);
            lbl_pelota2.setVisible(true);
        }
          if(count==8){
            lbl_pelota1.setVisible(true);
            lbl_pelota2.setVisible(false);
        }
         if(count==10){
            lbl_pelota1.setVisible(false);
            lbl_pelota2.setVisible(true);
        } 
         if(count==12){
            lbl_pelota1.setVisible(true);
            lbl_pelota2.setVisible(false);
        }
         if(count==14){
            lbl_pelota1.setVisible(false);
            lbl_pelota2.setVisible(true);
        }  
         if(count==16){
            lbl_pelota1.setVisible(true);
            lbl_pelota2.setVisible(false);
        }
         if(count==18){
            lbl_pelota1.setVisible(false);
            lbl_pelota2.setVisible(true);
        }  
         if(count==20){
            lbl_pelota1.setVisible(true);
            lbl_pelota2.setVisible(false);
         }
          
        String r = "0";
        Punto p = new Punto();
        String a = lbl_NumDer.getText();
        int b = p.Mas(Integer.parseInt(a));
        
        if(b<=11){
            lbl_NumDer.setText(Integer.toString(b));
            if(b==11){
                p2++;
                JOptionPane.showMessageDialog(null, "PUNTO!!");
                lbl_puntuacion2.setText(Integer.toString(p2));
                jp_tarjetaDer.setBackground(Color.WHITE);
                jp_tarjetaIzq.setBackground(Color.WHITE);
                lbl_NumIzq.setText(r);
                lbl_NumDer.setText(r);
            }
            
        }
    }//GEN-LAST:event_btn_MasDer1ActionPerformed

    private void btn_MenDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenDerActionPerformed
        // TODO add your handling code here:
        Punto p = new Punto();
        String a = lbl_NumDer.getText();
        int b = p.Menos(Integer.parseInt(a));
        
        if(b>=0){
            lbl_NumDer.setText(Integer.toString(b));
        }
    }//GEN-LAST:event_btn_MenDerActionPerformed

    private void btn_MasIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MasIzqActionPerformed
        // TODO add your handling code here:
        count++;
        String numero = String.valueOf(count);
        //prueba.setText(numero);
        if(count==2){
            lbl_pelota1.setVisible(false);
            lbl_pelota2.setVisible(true);
        }
        if(count==4){
            lbl_pelota1.setVisible(true);
            lbl_pelota2.setVisible(false);
        }
        if(count==6){
            lbl_pelota1.setVisible(false);
            lbl_pelota2.setVisible(true);
        }
          if(count==8){
            lbl_pelota1.setVisible(true);
            lbl_pelota2.setVisible(false);
        }
         if(count==10){
            lbl_pelota1.setVisible(false);
            lbl_pelota2.setVisible(true);
        }
         if(count==12){
            lbl_pelota1.setVisible(true);
            lbl_pelota2.setVisible(false);
        }
         if(count==14){
            lbl_pelota1.setVisible(false);
            lbl_pelota2.setVisible(true);
        }  
         if(count==16){
            lbl_pelota1.setVisible(true);
            lbl_pelota2.setVisible(false);
        }
         if(count==18){
            lbl_pelota1.setVisible(false);
            lbl_pelota2.setVisible(true);
        }  
         if(count==20){
            lbl_pelota1.setVisible(true);
            lbl_pelota2.setVisible(false);
         }
        
        String r = "0";
        Punto p = new Punto();
        String a = lbl_NumIzq.getText();
        int b = p.Mas(Integer.parseInt(a));
        
        if(b<=11){
            lbl_NumIzq.setText(Integer.toString(b));
            if(b==11){
                ne++;
                JOptionPane.showMessageDialog(null, "PUNTO!!");
                lbl_puntuacion1.setText(Integer.toString(ne));
                jp_tarjetaDer.setBackground(Color.WHITE);
                jp_tarjetaIzq.setBackground(Color.WHITE);
                lbl_NumIzq.setText(r);
                lbl_NumDer.setText(r);
            }
        }
    }//GEN-LAST:event_btn_MasIzqActionPerformed

    private void btn_MenIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenIzqActionPerformed
        // TODO add your handling code here:
        Punto p = new Punto();
        String a = lbl_NumIzq.getText();
        int b = p.Menos(Integer.parseInt(a));
        
        if(b>=0){
            lbl_NumIzq.setText(Integer.toString(b));
        }
    }//GEN-LAST:event_btn_MenIzqActionPerformed
    //Inicializa el cronometro
    
    
    private void btn_minJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minJ1ActionPerformed
        // TODO add your handling code here:
        int ax = JOptionPane.showConfirmDialog(null, "Esta Seguro de solicitar minuto");
        if(ax == JOptionPane.YES_OPTION){
            // Instancia al formulario cronometro..
            Cronometro cr = new Cronometro();
            cr.setVisible(true);
            btn_minJ1.setEnabled(false);
        }
    }//GEN-LAST:event_btn_minJ1ActionPerformed

    private void btn_minJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minJ2ActionPerformed
        // TODO add your handling code here:
        int ax = JOptionPane.showConfirmDialog(null, "Esta Seguro de solicitar minuto");
        if(ax == JOptionPane.YES_OPTION){
            // Instancia al formulario cronometro..
            Cronometro cr = new Cronometro();
            cr.setVisible(true);
            btn_minJ2.setEnabled(false);
        }
    }//GEN-LAST:event_btn_minJ2ActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void jp_tarjetaIzqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_tarjetaIzqMouseClicked
        // TODO add your handling code here:
        String r = "0";
        
        if(cont<=2){
            
            jp_tarjetaIzq.setBackground(Color.YELLOW);
            if(cont==2){
                jp_tarjetaIzq.setBackground(Color.red);
                JOptionPane.showMessageDialog(this, "EXPULSADO");
                jp_tarjetaDer.setBackground(Color.WHITE);
                jp_tarjetaIzq.setBackground(Color.WHITE);
                lbl_NumIzq.setText(r);
                lbl_NumDer.setText(r);
            }
        }  cont++;
    }//GEN-LAST:event_jp_tarjetaIzqMouseClicked

    private void jp_tarjetaDerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_tarjetaDerMouseClicked
        // TODO add your handling code here:
        String r = "0";
        
        if(coun<=2){
            
            jp_tarjetaDer.setBackground(Color.YELLOW);
            if(coun==2){
                jp_tarjetaDer.setBackground(Color.red);
                JOptionPane.showMessageDialog(this, "EXPULSADO");
                jp_tarjetaDer.setBackground(Color.WHITE);
                jp_tarjetaIzq.setBackground(Color.WHITE);
                lbl_NumIzq.setText(r);
                lbl_NumDer.setText(r);
            }
        }  coun++;
    }//GEN-LAST:event_jp_tarjetaDerMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Config c = new Config();
        c.setVisible(true);
        
        //this.dispose();
        String j1 = lbl_jugador1.getText();
        String j2 = lbl_jugador2.getText();
        c.lbl_jug1.setText(j1);
        c.lbl_jug2.setText(j2);
        //btn_play.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private int coun=1;    
    private int cont=1;
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
               
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MasDer1;
    private javax.swing.JButton btn_MasIzq;
    private javax.swing.JButton btn_MenDer;
    private javax.swing.JButton btn_MenIzq;
    public javax.swing.JButton btn_minJ1;
    private javax.swing.JButton btn_minJ2;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jp_tarjetaDer;
    public javax.swing.JPanel jp_tarjetaIzq;
    public javax.swing.JPanel jpvista1;
    public javax.swing.JPanel jpvista2;
    public javax.swing.JPanel jpvista3;
    public javax.swing.JPanel jpvista4;
    public javax.swing.JPanel jpvista5;
    public javax.swing.JPanel jpvista7;
    public javax.swing.JPanel jpvistaDerech;
    public javax.swing.JPanel jpvistaIzq;
    private javax.swing.JLabel lbl_NumDer;
    private javax.swing.JLabel lbl_NumIzq;
    public javax.swing.JLabel lbl_cronoPartido;
    public javax.swing.JLabel lbl_horaAct1;
    public javax.swing.JLabel lbl_jset;
    public javax.swing.JLabel lbl_jugador1;
    public javax.swing.JLabel lbl_jugador2;
    public javax.swing.JLabel lbl_pelota1;
    public javax.swing.JLabel lbl_pelota2;
    private javax.swing.JLabel lbl_puntuacion1;
    private javax.swing.JLabel lbl_puntuacion2;
    public javax.swing.JLabel lbl_set;
    // End of variables declaration//GEN-END:variables
}

