/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Clases.CambiaPanel;
import paneles.inicio;
/**
 *
 * @author ProgInit
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        new CambiaPanel(jp_centro, new paneles.inicio());
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jp_n1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_max = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btn_menusv = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jp_n2 = new javax.swing.JPanel();
        btn_inicio = new javax.swing.JButton();
        btn_registro = new javax.swing.JButton();
        btn_administrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_diagrama1 = new javax.swing.JButton();
        jp_centro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(0, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_n1.setBackground(new java.awt.Color(0, 51, 51));
        jp_n1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jp_n1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/hombre-jugando-al-ping-pong.png"))); // NOI18N
        jp_n1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/dos-raquetas-de-ping-pong.png"))); // NOI18N
        jp_n1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/man-jugando-ping-pong.png"))); // NOI18N
        jp_n1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        btn_max.setBackground(new java.awt.Color(0, 51, 51));
        btn_max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pantalla-completa.png"))); // NOI18N
        btn_max.setBorder(null);
        btn_max.setBorderPainted(false);
        btn_max.setContentAreaFilled(false);
        btn_max.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_n1.add(btn_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 20, 20));

        jButton6.setBackground(new java.awt.Color(0, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jp_n1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 20, 20));

        btn_menusv.setBackground(new java.awt.Color(0, 51, 51));
        btn_menusv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/menu.png"))); // NOI18N
        btn_menusv.setBorder(null);
        btn_menusv.setBorderPainted(false);
        btn_menusv.setContentAreaFilled(false);
        btn_menusv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menusv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menusvActionPerformed(evt);
            }
        });
        jp_n1.add(btn_menusv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        jButton7.setBackground(new java.awt.Color(0, 51, 51));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menos.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jp_n1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 20, 20));

        jPanel4.add(jp_n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 50));

        jp_n2.setBackground(new java.awt.Color(0, 51, 51));
        jp_n2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio.setBackground(new java.awt.Color(0, 51, 51));
        btn_inicio.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        btn_inicio.setForeground(new java.awt.Color(204, 204, 204));
        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/boton-de-inicio.png"))); // NOI18N
        btn_inicio.setText("Inicio");
        btn_inicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_inicio.setContentAreaFilled(false);
        btn_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_inicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_inicio.setIconTextGap(18);
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });
        jp_n2.add(btn_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 140, 40));

        btn_registro.setBackground(new java.awt.Color(255, 255, 255));
        btn_registro.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        btn_registro.setForeground(new java.awt.Color(255, 255, 255));
        btn_registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/formulario.png"))); // NOI18N
        btn_registro.setText("Registros");
        btn_registro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_registro.setContentAreaFilled(false);
        btn_registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_registro.setIconTextGap(18);
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });
        jp_n2.add(btn_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 140, 40));

        btn_administrar.setBackground(new java.awt.Color(255, 255, 255));
        btn_administrar.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        btn_administrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_administrar.setText("Administrar");
        btn_administrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_administrar.setContentAreaFilled(false);
        btn_administrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_administrar.setIconTextGap(15);
        btn_administrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administrarActionPerformed(evt);
            }
        });
        jp_n2.add(btn_administrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 140, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/trabpc.png"))); // NOI18N
        jp_n2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 70, 70));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADMIN");
        jp_n2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        btn_diagrama1.setBackground(new java.awt.Color(255, 255, 255));
        btn_diagrama1.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        btn_diagrama1.setForeground(new java.awt.Color(255, 255, 255));
        btn_diagrama1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/diagrama.png"))); // NOI18N
        btn_diagrama1.setText("Diagrama");
        btn_diagrama1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btn_diagrama1.setContentAreaFilled(false);
        btn_diagrama1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_diagrama1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_diagrama1.setIconTextGap(15);
        btn_diagrama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diagrama1ActionPerformed(evt);
            }
        });
        jp_n2.add(btn_diagrama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 140, 40));

        jPanel4.add(jp_n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 140, 390));

        jp_centro.setBackground(new java.awt.Color(255, 255, 255));
        jp_centro.setForeground(new java.awt.Color(0, 51, 51));
        jp_centro.setLayout(new javax.swing.BoxLayout(jp_centro, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(jp_centro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 640, 390));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_menusvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menusvActionPerformed
        // TODO add your handling code here:
        int posicion = this.jp_n2.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -140, 2, 2, jp_n2);
        }else{
            Animacion.Animacion.mover_derecha(-140, 0, 2, 2, jp_n2);
        }
    }//GEN-LAST:event_btn_menusvActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(jp_centro, new paneles.inicio());
        System.out.println("hola mundo");
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(jp_centro, new paneles.registro());
    }//GEN-LAST:event_btn_registroActionPerformed

    private void btn_administrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administrarActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(jp_centro, new paneles.admin());
    }//GEN-LAST:event_btn_administrarActionPerformed

    private void btn_diagrama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diagrama1ActionPerformed
        // TODO add your handling code here:
       new CambiaPanel(jp_centro, new paneles.diagrama());
    }//GEN-LAST:event_btn_diagrama1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_administrar;
    private javax.swing.JButton btn_diagrama1;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_max;
    private javax.swing.JButton btn_menusv;
    private javax.swing.JButton btn_registro;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jp_centro;
    private javax.swing.JPanel jp_n1;
    private javax.swing.JPanel jp_n2;
    // End of variables declaration//GEN-END:variables
}
