/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexion.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Jlse
 */
public class GruposDe4 extends javax.swing.JFrame {

    /**
     * Creates new form GruposDe4
     */
    public GruposDe4() {
        initComponents();
        Llenarlista();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaG1 = new javax.swing.JList<>();
        J1G1 = new javax.swing.JLabel();
        J11G1 = new javax.swing.JLabel();
        J111G1 = new javax.swing.JLabel();
        J2G1 = new javax.swing.JLabel();
        J22G1 = new javax.swing.JLabel();
        J3G1 = new javax.swing.JLabel();
        J222G1 = new javax.swing.JLabel();
        J33G1 = new javax.swing.JLabel();
        J4G1 = new javax.swing.JLabel();
        J333G1 = new javax.swing.JLabel();
        J44G1 = new javax.swing.JLabel();
        J444G1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaG3 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaG4 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaG2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Grupo 1"));

        jScrollPane1.setViewportView(listaG1);

        J1G1.setText("jLabel1");

        J11G1.setText("jLabel2");

        J111G1.setText("jLabel3");

        J2G1.setText("jLabel4");

        J22G1.setText("jLabel5");

        J3G1.setText("jLabel6");

        J222G1.setText("jLabel7");

        J33G1.setText("jLabel8");

        J4G1.setText("jLabel9");

        J333G1.setText("jLabel10");

        J44G1.setText("jLabel11");

        J444G1.setText("jLabel12");

        jLabel13.setText("VS");

        jLabel14.setText("VS");

        jLabel15.setText("VS");

        jLabel16.setText("VS");

        jLabel17.setText("VS");

        jLabel18.setText("VS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J1G1)
                            .addComponent(J3G1)
                            .addComponent(J22G1)
                            .addComponent(J2G1)
                            .addComponent(J111G1)
                            .addComponent(J11G1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J222G1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(J444G1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(J44G1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(J333G1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(J33G1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(J4G1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J1G1)
                    .addComponent(J222G1)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J11G1)
                    .addComponent(J33G1)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J111G1)
                    .addComponent(J4G1)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J2G1)
                    .addComponent(J333G1)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J22G1)
                    .addComponent(J44G1)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J3G1)
                    .addComponent(J444G1)
                    .addComponent(jLabel14))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Grupo 3"));

        jScrollPane3.setViewportView(listaG3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Grupo 4"));

        jScrollPane4.setViewportView(listaG4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Grupo 2"));

        jScrollPane2.setViewportView(listaG2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void Llenarlista(){
        DefaultListModel lista1 = new DefaultListModel();
        DefaultListModel lista2 = new DefaultListModel();
        DefaultListModel lista3 = new DefaultListModel();
        DefaultListModel lista4 = new DefaultListModel();
        //String []datos = new String[4];
        Conexion cn = new Conexion();
        cn.getConexion();
        
        ResultSet rs = cn.consulta("SELECT CI,NOMBRE,APELLIDO,RANKING FROM JUGADORTORNEO ORDER BY RANKING DESC");
        try {
            //while (rs.next()) {
                rs.next();
                lista1.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista2.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista3.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista4.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista4.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista3.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista2.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista1.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista1.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista2.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista3.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista4.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista4.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista3.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista2.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
                rs.next();
                lista1.addElement(rs.getString(1)+" - "+rs.getString(2)+" "+rs.getString(3)+" - "+rs.getString(4));
            //}
            listaG1.setModel(lista1);
            //System.out.println(" "+lista1.elementAt(0));
            listaG2.setModel(lista2);
            listaG3.setModel(lista3);
            listaG4.setModel(lista4);
            
            J1G1.setText(((String) lista1.elementAt(0)).substring(0, 9));
            J11G1.setText(((String) lista1.elementAt(0)).substring(0, 9));
            J111G1.setText(((String) lista1.elementAt(0)).substring(0, 9));
            J2G1.setText(((String) lista1.elementAt(1)).substring(0, 9));
            J22G1.setText(((String) lista1.elementAt(1)).substring(0, 9));
            J222G1.setText(((String) lista1.elementAt(1)).substring(0, 9));
            J3G1.setText(((String) lista1.elementAt(2)).substring(0, 9));
            J33G1.setText(((String) lista1.elementAt(2)).substring(0, 9));
            J333G1.setText(((String) lista1.elementAt(2)).substring(0, 9));
            J4G1.setText(((String) lista1.elementAt(3)).substring(0, 9));
            J44G1.setText(((String) lista1.elementAt(3)).substring(0, 9));
            J444G1.setText(((String) lista1.elementAt(3)).substring(0, 9));
        } catch (SQLException ex) {
            Logger.getLogger(seleccionarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GruposDe4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GruposDe4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GruposDe4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GruposDe4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GruposDe4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J111G1;
    private javax.swing.JLabel J11G1;
    private javax.swing.JLabel J1G1;
    private javax.swing.JLabel J222G1;
    private javax.swing.JLabel J22G1;
    private javax.swing.JLabel J2G1;
    private javax.swing.JLabel J333G1;
    private javax.swing.JLabel J33G1;
    private javax.swing.JLabel J3G1;
    private javax.swing.JLabel J444G1;
    private javax.swing.JLabel J44G1;
    private javax.swing.JLabel J4G1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listaG1;
    private javax.swing.JList<String> listaG2;
    private javax.swing.JList<String> listaG3;
    private javax.swing.JList<String> listaG4;
    // End of variables declaration//GEN-END:variables
}
