/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexion.Conexion;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jlse
 */
public class partido extends javax.swing.JFrame {
    
    Conexion cn = new Conexion();
    public int n = 0;

    /**
     * Creates new form partido
     */
    public partido() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        //llenarCombo1();
        //llenarCombo2();
        //llenarCombo3();
       // llenarCombo4();
       // actions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDirec = new javax.swing.JTextField();
        cbxFase = new javax.swing.JComboBox<>();
        cbxTorneo = new javax.swing.JComboBox<>();
        ftxtFecha = new javax.swing.JFormattedTextField();
        FtxtHora = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LbNumMesa = new javax.swing.JLabel();
        jlbArbitro = new javax.swing.JLabel();
        jlbJugador1 = new javax.swing.JLabel();
        jlbJugador2 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del Partido");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mesa:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Direccion:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fase:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Torneo:");

        cbxFase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Fase", "Final", "Semi-Final", "Cuartos_Final", "Octavos_Final", "16_Final", "32_Final" }));

        try {
            ftxtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            FtxtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DD/MM/AAAA");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("HH:MM:SS 24Hr.");

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setForeground(new java.awt.Color(0, 51, 51));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevo.setForeground(new java.awt.Color(0, 51, 51));
        btnNuevo.setText("Nuevo");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Arbitro:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jugador 1:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jugador 2:");

        LbNumMesa.setForeground(new java.awt.Color(255, 255, 255));
        LbNumMesa.setText("jLabel13");

        jlbArbitro.setForeground(new java.awt.Color(255, 255, 255));
        jlbArbitro.setText("jLabel13");

        jlbJugador1.setForeground(new java.awt.Color(255, 255, 255));
        jlbJugador1.setText("jLabel13");

        jlbJugador2.setForeground(new java.awt.Color(255, 255, 255));
        jlbJugador2.setText("jLabel13");

        btn_salir.setBackground(new java.awt.Color(0, 51, 51));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar.png"))); // NOI18N
        btn_salir.setBorder(null);
        btn_salir.setBorderPainted(false);
        btn_salir.setContentAreaFilled(false);
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addComponent(ftxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(22, 22, 22)
                        .addComponent(FtxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbJugador2)
                            .addComponent(jlbJugador1)
                            .addComponent(jlbArbitro)
                            .addComponent(cbxTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(LbNumMesa)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20)
                        .addComponent(cbxFase, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(LbNumMesa)
                            .addComponent(jLabel6))))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ftxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(FtxtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuardar))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnNuevo)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addComponent(cbxTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlbArbitro))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jlbJugador1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jlbJugador2))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        switch(n){
            case 1 : {
                GruposDe4.jlbFecha1.setText(ftxtFecha.getText());
                GruposDe4.jlbHora1.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            case 2 : {
                GruposDe4.jlbFecha2.setText(ftxtFecha.getText());
                GruposDe4.jlbHora2.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            case 3 : {
                GruposDe4.jlbFecha3.setText(ftxtFecha.getText());
                GruposDe4.jlbHora3.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            case 4 : {
                GruposDe4.jlbFecha4.setText(ftxtFecha.getText());
                GruposDe4.jlbHora4.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            case 5 : {
                GruposDe4.jlbFecha5.setText(ftxtFecha.getText());
                GruposDe4.jlbHora5.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            case 6 : {
                GruposDe4.jlbFecha6.setText(ftxtFecha.getText());
                GruposDe4.jlbHora6.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            case 7 : {
                GruposDe4.jlbFecha7.setText(ftxtFecha.getText());
                GruposDe4.jlbHora7.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            case 8 : {
                GruposDe4.jlbFecha8.setText(ftxtFecha.getText());
                GruposDe4.jlbHora8.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            case 9 : {
                GruposDe4.jlbFecha9.setText(ftxtFecha.getText());
                GruposDe4.jlbHora9.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            case 10 : {
                GruposDe4.jlbFecha10.setText(ftxtFecha.getText());
                GruposDe4.jlbHora10.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            case 11 : {
                GruposDe4.jlbFecha11.setText(ftxtFecha.getText());
                GruposDe4.jlbHora11.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            case 12 : {
                GruposDe4.jlbFecha12.setText(ftxtFecha.getText());
                GruposDe4.jlbHora12.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 13 : {
                GruposDe4.jlbFecha16.setText(ftxtFecha.getText());
                GruposDe4.jlbHora14.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 14 : {
                GruposDe4.jlbFecha17.setText(ftxtFecha.getText());
                GruposDe4.jlbHora18.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 15 : {
                GruposDe4.jlbFecha18.setText(ftxtFecha.getText());
                GruposDe4.jlbHora16.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 16 : {
                GruposDe4.jlbFecha15.setText(ftxtFecha.getText());
                GruposDe4.jlbHora13.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 17 : {
                GruposDe4.jlbFecha14.setText(ftxtFecha.getText());
                GruposDe4.jlbHora15.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 18 : {
                GruposDe4.jlbFecha13.setText(ftxtFecha.getText());
                GruposDe4.jlbHora17.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 19 : {
                GruposDe4.jlbFecha22.setText(ftxtFecha.getText());
                GruposDe4.jlbHora20.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 20 : {
                GruposDe4.jlbFecha23.setText(ftxtFecha.getText());
                GruposDe4.jlbHora24.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 21 : {
                GruposDe4.jlbFecha24.setText(ftxtFecha.getText());
                GruposDe4.jlbHora22.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 22 : {
                GruposDe4.jlbFecha21.setText(ftxtFecha.getText());
                GruposDe4.jlbHora19.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 23 : {
                GruposDe4.jlbFecha20.setText(ftxtFecha.getText());
                GruposDe4.jlbHora21.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
            
            case 24 : {
                GruposDe4.jlbFecha19.setText(ftxtFecha.getText());
                GruposDe4.jlbHora23.setText(FtxtHora.getText());
                this.dispose();
                break;
            }
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed
    
    
    //Llena el comboBox Torneo 
    private void llenarCombo1(){
        String sql = "select ID_T,DETALLE from TORNEO";
        cn.getConexion();
        ResultSet rs = cn.consulta(sql);
        try {
            //Añade nuevo item al cbxTorneo
            while(rs.next()){
                cbxTorneo.addItem(rs.getString(1)+" - "+rs.getString(2));
                //System.out.println(rs.getString(1)+" - "+rs.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(partido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //Llena comboBox Arbitro
    /*private void llenarCombo2(){
        String sql = "select CI_A,NOMBRE from Arbitro";
        cn.getConexion();
        ResultSet rs = cn.consulta(sql);
        try {
            while(rs.next()){
                jcbArbitro.addItem(rs.getString(1)+" - "+rs.getString(2));
            }
        } catch (Exception e) {
            Logger.getLogger(partido.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void llenarCombo3(){
        String sql = "select CI_J, NOMBRE from JUGADOR";
        cn.getConexion();
        ResultSet rs = cn.consulta(sql);
        try {
            while(rs.next()){
                jcbJugador1.addItem(rs.getString(1)+" - "+rs.getString(2));
            }
        } catch (Exception e) {
            Logger.getLogger(partido.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void llenarCombo4(){
        String sql = "select CI_J, NOMBRE from JUGADOR";
        cn.getConexion();
        ResultSet rs = cn.consulta(sql);
        try {
            while(rs.next()){
                jcbJugador2.addItem(rs.getString(1)+" - "+rs.getString(2));
            }
        } catch (Exception e) {
            Logger.getLogger(partido.class.getName()).log(Level.SEVERE, null, e);
        }
    } */
    
    /*public void actions(){
        final ItemListener changeClick = new ItemListener() {
          @Override
          public void itemStateChanged(ItemEvent ie) {
                
                if(jcbArbitro.getSelectedItem().equals(ie.getItem())){
                  if(ie.getItem().toString().equals("Nuevo Arbitro")){
                      // Instancia al formulario arbitro
                      arbitro ar = new arbitro();
                      ar.setVisible(true);
                  }
                }
                if(jcbJugador1.getSelectedItem().equals(ie.getItem())){
                    if(ie.getItem().toString().equals("Nuevo Jugador")){
                        System.out.println("Jugador 1");
                        // Instancia al formulario de jugador
                        jugador ju = new jugador();
                        ju.setVisible(true);
                    }
                }
                /*if(jcbJugador2.getSelectedItem().equals(ie.getItem())){
                    if(ie.getItem().toString().equals("Nuevo Jugador")){
                        System.out.println("Jugador 2");
                        // Instancia al formulario de jugador
                        jugador ju = new jugador();
                        ju.setVisible(true);
                    }
                }*/ /*
            }
        };
        this.jcbArbitro.addItemListener(changeClick);
        this.jcbJugador1.addItemListener(changeClick); 
        this.jcbJugador2.addItemListener(changeClick); 
    } */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new partido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FtxtHora;
    public javax.swing.JLabel LbNumMesa;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbxFase;
    private javax.swing.JComboBox<String> cbxTorneo;
    private javax.swing.JFormattedTextField ftxtFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jlbArbitro;
    public javax.swing.JLabel jlbJugador1;
    public javax.swing.JLabel jlbJugador2;
    private javax.swing.JTextField txtDirec;
    // End of variables declaration//GEN-END:variables
}
