/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexion.Conexion;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jlse
 */
public class partido extends javax.swing.JFrame {
    
    Conexion cn = new Conexion();

    /**
     * Creates new form partido
     */
    public partido() {
        this.setLocationRelativeTo(null);
        initComponents();
        llenarCombo1();
        llenarCombo2();
        llenarCombo3();
        llenarCombo4();
        actions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDirec = new javax.swing.JTextField();
        cbxFase = new javax.swing.JComboBox<>();
        cbxTorneo = new javax.swing.JComboBox<>();
        cbxMesa = new javax.swing.JComboBox<>();
        ftxtFecha = new javax.swing.JFormattedTextField();
        FtxtHora = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jcbArbitro = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcbJugador1 = new javax.swing.JComboBox<>();
        jcbJugador2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Datos del Partido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 6, 129, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Mesa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Fecha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 119, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Hora:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 119, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Direccion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 165, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Fase:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Torneo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 217, -1, -1));

        txtDirec.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 160, 274, -1));

        cbxFase.setBackground(new java.awt.Color(255, 255, 255));
        cbxFase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Fase", "Final", "Semi-Final", "Cuartos_Final", "Octavos_Final", "16_Final", "32_Final" }));
        jPanel1.add(cbxFase, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 44, 127, -1));

        cbxTorneo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(cbxTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 211, 274, -1));

        cbxMesa.setBackground(new java.awt.Color(255, 255, 255));
        cbxMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(cbxMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 44, -1, -1));

        ftxtFecha.setBackground(new java.awt.Color(255, 255, 255));
        try {
            ftxtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(ftxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 116, 93, -1));

        FtxtHora.setBackground(new java.awt.Color(255, 255, 255));
        try {
            FtxtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(FtxtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 116, 124, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DD/MM/AAAA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 88, 93, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("HH:MM:SS 24Hr.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 88, 124, -1));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setForeground(new java.awt.Color(0, 51, 51));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 110, -1, -1));

        btnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevo.setForeground(new java.awt.Color(0, 51, 51));
        btnNuevo.setText("Nuevo");
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 173, 76, -1));

        jcbArbitro.setBackground(new java.awt.Color(255, 255, 255));
        jcbArbitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Arbitro", "Nuevo Arbitro" }));
        jPanel1.add(jcbArbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 255, 274, -1));

        jLabel10.setText("Arbitro:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 260, -1, -1));

        jLabel11.setText("Jugador 1:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 304, -1, -1));

        jLabel12.setText("Jugador 2:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 348, -1, -1));

        jcbJugador1.setBackground(new java.awt.Color(255, 255, 255));
        jcbJugador1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Jugador", "Nuevo Jugador", "1", "2", "3", "4" }));
        jPanel1.add(jcbJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 299, 274, -1));

        jcbJugador2.setBackground(new java.awt.Color(255, 255, 255));
        jcbJugador2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Jugador", "Nuevo Jugador", "1", "2", "3", "4", "5" }));
        jPanel1.add(jcbJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 343, 274, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int NumMesa = Integer.parseInt((String) cbxMesa.getSelectedItem());
        String fase = (String) cbxFase.getSelectedItem();
        String fecha = ftxtFecha.getText();
        String hora = FtxtHora.getText();
        String direc = txtDirec.getText();
        String ci_a = (String) jcbArbitro.getSelectedItem();
        String ci_j1 = (String) jcbJugador1.getSelectedItem();
        String ci_j2 = (String) jcbJugador2.getSelectedItem();
        String torneo = (String) cbxTorneo.getSelectedItem();
        int numIndexA = ci_a.indexOf("-");
        int numIndexJ1 = ci_j1.indexOf("-");
        int numIndexJ2 = ci_j2.indexOf("-");
        int numIndexT = torneo.indexOf("-");
        String ci_a1 = ci_a.substring(0,numIndexA-1);
        String ci_j11 = ci_j1.substring(0,numIndexJ1-1);
        String ci_j21 = ci_j2.substring(0, numIndexJ2-1);
        int torneo1 = Integer.parseInt(torneo.substring(0, numIndexT-1));
        cn.getConexion();
        cn.Inseratar("insert into PARTIDO (NUMMESA,FECHA,HORA,DIRECCION,FASE,CI_A,CI_J1,CI_J2,ID_T) values("+NumMesa+",'"+fecha+"','"+hora+"','"+direc+"','"+fase+"','"+ci_a1+"','"+ci_j11+"','"+ci_j21+"',"+torneo1+")");
        System.out.println(NumMesa+" "+fase+" "+hora+" "+fecha+" "+torneo1+" "+ci_a1+" "+ci_j11+" "+ci_j21);
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    //Llena el comboBox Torneo 
    private void llenarCombo1(){
        String sql = "select ID_T,DETALLE from TORNEO";
        cn.getConexion();
        ResultSet rs = cn.consulta(sql);
        try {
            //Añade nuevo item al cbxTorneo
            while(rs.next()){
                cbxTorneo.addItem(rs.getString(1)+" - "+rs.getString(2));
                //System.out.println(rs.getString(1)+" - "+rs.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(partido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //Llena comboBox Arbitro
    private void llenarCombo2(){
        String sql = "select CI_A,NOMBRE from Arbitro";
        cn.getConexion();
        ResultSet rs = cn.consulta(sql);
        try {
            while(rs.next()){
                jcbArbitro.addItem(rs.getString(1)+" - "+rs.getString(2));
            }
        } catch (Exception e) {
            Logger.getLogger(partido.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void llenarCombo3(){
        String sql = "select CI_J, NOMBRE from JUGADOR";
        cn.getConexion();
        ResultSet rs = cn.consulta(sql);
        try {
            while(rs.next()){
                jcbJugador1.addItem(rs.getString(1)+" - "+rs.getString(2));
            }
        } catch (Exception e) {
            Logger.getLogger(partido.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void llenarCombo4(){
        String sql = "select CI_J, NOMBRE from JUGADOR";
        cn.getConexion();
        ResultSet rs = cn.consulta(sql);
        try {
            while(rs.next()){
                jcbJugador2.addItem(rs.getString(1)+" - "+rs.getString(2));
            }
        } catch (Exception e) {
            Logger.getLogger(partido.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    public void actions(){
        final ItemListener changeClick = new ItemListener() {
          @Override
          public void itemStateChanged(ItemEvent ie) {
                
                if(jcbArbitro.getSelectedItem().equals(ie.getItem())){
                  if(ie.getItem().toString().equals("Nuevo Arbitro")){
                      // Instancia al formulario arbitro
                      arbitro ar = new arbitro();
                      ar.setVisible(true);
                  }
                }
                if(jcbJugador1.getSelectedItem().equals(ie.getItem())){
                    if(ie.getItem().toString().equals("Nuevo Jugador")){
                        System.out.println("Jugador 1");
                        // Instancia al formulario de jugador
                        jugador ju = new jugador();
                        ju.setVisible(true);
                    }
                }
                /*if(jcbJugador2.getSelectedItem().equals(ie.getItem())){
                    if(ie.getItem().toString().equals("Nuevo Jugador")){
                        System.out.println("Jugador 2");
                        // Instancia al formulario de jugador
                        jugador ju = new jugador();
                        ju.setVisible(true);
                    }
                }*/
            }
        };
        this.jcbArbitro.addItemListener(changeClick);
        this.jcbJugador1.addItemListener(changeClick); 
        this.jcbJugador2.addItemListener(changeClick); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new partido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField FtxtHora;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbxFase;
    private javax.swing.JComboBox<String> cbxMesa;
    private javax.swing.JComboBox<String> cbxTorneo;
    private javax.swing.JFormattedTextField ftxtFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbArbitro;
    private javax.swing.JComboBox<String> jcbJugador1;
    private javax.swing.JComboBox<String> jcbJugador2;
    private javax.swing.JTextField txtDirec;
    // End of variables declaration//GEN-END:variables
}
